#!/bin/bash

echo "Running Spotless..."
./gradlew spotlessApply --rerun-tasks

# Add files that might have been changed by Spotless back to the commit
git add .

echo "Running Lint..."
./gradlew lint

# Capture the exit code of lint
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "Lint failed! Please fix errors before committing."
    exit $EXIT_CODE
fi

exit 0
